### ISSUE TITLE
read browsing history permission

### ISSUE THREAD

**Issue by kirsan31** [ForNeVeR/msdn-delocalizer#27]
Hi. For what read browsing history permission is needed?
![image](https://user-images.githubusercontent.com/17767561/198191194-46c56652-909f-445f-b851-bfd509e07de8.png)
Foe example [FFS MSDN in English](https://chrome.google.com/webstore/detail/ffs-msdn-in-english/ddaknggefjjgpnlhiejepbiplceedmfl) doesn't need it.
Thanks.

**Comment by ForNeVeR** [comment]
That's a good question.

The plugin uses the `tabs` permission, which Chrome seems to interpret as a "Read your browsing history".

What we actually use the permission is to access the `chrome.tabs.onUpdated` event: https://github.com/ForNeVeR/msdn-delocalizer/blob/05c052f1f7a682ac05066848c34e8706a3139035/src/background.ts#L5

Technically, since we observe all the tab URL changes, it's possible for the plugin to collect your browsing history and do something bad with it (though since the plugin doesn't do any script injection and doesn't require network access, I'm not sure it's possible to do anything bad – but I have to note I am not a browser plugin expert, and may be incorrectly interpreting some permissions).

Fro a quick look, **FFS MSDN in English** (an older alternative to my plugin, which I respect) seems to use script injection instead, which is (to me at least) a less clean solution, and requires a different set of permissions.

If this is a blocker for you, and/or you see a better solution, feel free to drop a comment.
